### ISSUE TITLE
Including Service Bindings for nginx.conf and mime.types

### ISSUE THREAD

**Issue by voor** [paketo-buildpacks/nginx#281]
## What happened?

I would like to inject a nginx.conf file and mime.types from a common location using https://github.com/buildpacks/spec/blob/main/extensions/bindings.md so that I do not need developers to commit this into source code. 

## Build Configuration

`gcr.io/paketo-buildpacks/nginx:0.3.1`

pack and Tanzu Build Service (kpack)

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

nginx.conf: https://github.com/voor/static-build-service-template/blob/5cfaac6b3b4dec9e5238ea290a866bed52b5c369/nginx.conf
mime.types: https://github.com/voor/static-build-service-template/blob/5cfaac6b3b4dec9e5238ea290a866bed52b5c369/mime.types

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by arjun024** [comment]
@voor It's possible to add such a feature but I'm wondering about the value of such a feature. Bindings are typically used for secrets that users do not/cannot check-in with the their app. Is there a compelling reason to avoid checking in configuration files?

**Comment by voor** [comment]
Yes, different teams are responsible for the hand-off, and we do not want the consumers of the buildpack to change them, if the files are present in the users repository they might accidentally modify or delete it, causing significant issues in the build process.

Additionally, if we need to change the files we would need to go to all of the consumers and make sure the file is updated accordingly.

**Comment by dmikusa-pivotal** [comment]
+1 for this. I haven't tried it, but I think you can use a ConfigMap instead of a secret with a binding. The binding just has to be mapped into the file system in the expected location. I'm pretty sure this is common practice with Nginx config, to pass it in through volume mounts.

**Comment by voor** [comment]
I'm using kpack syntax for this, but I'd be looking for something like this:

```
apiVersion: kpack.io/v1alpha1
kind: Image
metadata:
  name: simple-static-app
  namespace: default
spec:
  build:
    bindings:
    - name: nginx
      secretRef:
        name: nginx-config
      metadataRef:
        name: settings-binding-metadata
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings-binding-metadata
data:
  kind: nginx
  provider: nginx
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-config
type: Opaque
stringData:
  mime.types: |
    types {
        ...
    }
  nginx.confg: |
    worker_processes  5;  ## Default: 1
    daemon off;
    worker_rlimit_nofile 8192;
    ...
```
