### ISSUE TITLE
Add support for the tiny stack

### ISSUE THREAD

**Issue by voor** [paketo-buildpacks/nginx#283]
## What happened?

* What were you attempting to do?

I want to use the tiny stack with the nginx buildpack, because I want to have a very minimalist image.

* What did you expect to happen?

nginx would happily run on tiny.

* What was the actual behavior? Please provide log output, if possible.

'validating buildpack paketo-buildpacks/nginx@0.3.1: stack io.paketo.stacks.tiny is not supported'

## Build Configuration

```
apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: node-script-builder
spec:
  order:
  - group:
    - id: paketo-buildpacks/nodejs
    - id: paketo-buildpacks/nginx
    - id: source-removal
  serviceAccountRef:
    name: default
    namespace: default
  stack:
    kind: ClusterStack
    name: default #! Make sure tiny is properly loaded from the dependency syncer.
  store:
    kind: ClusterStore
    name: node-cluster-store
  tag: #@ "{}/node-script-builder:0.0.1".format(data.values.docker_repository)
```

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

kpack released with Tanzu Build Service 1.2.2

* What buildpacks are you using? Please include versions.

`gcr.io/paketo-buildpacks/nginx:0.3.1`

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.
